"""
waf_detect.py — Ultra WAF Detection & Bypass Engine
Features: 35+ WAF vendors, behavioral analysis, cookie/header/response fingerprinting,
          bypass technique suggestions, CDN detection, rate limit detection
"""

import re
import socket
import time
from typing import Dict, List, Optional, Tuple

import requests
import urllib3
urllib3.disable_warnings()

from ui.rich_ui import (
    console, info, warning, error, found, success, section_header, print_summary
)

TIMEOUT = 10

# ── WAF signatures ────────────────────────────────────────────────────────────
WAF_SIGNATURES: List[Dict] = [
    # Headers
    {"name": "Cloudflare",      "type": "header",   "header": "cf-ray",                  "pattern": r".*"},
    {"name": "Cloudflare",      "type": "header",   "header": "server",                  "pattern": r"cloudflare"},
    {"name": "Cloudflare",      "type": "cookie",   "cookie": "cf_clearance",            "pattern": r".*"},
    {"name": "Cloudflare",      "type": "body",     "pattern": r"cloudflare.*ray\s+id|attention required.*cloudflare"},
    {"name": "AWS WAF",         "type": "header",   "header": "x-amzn-requestid",        "pattern": r".*"},
    {"name": "AWS WAF",         "type": "body",     "pattern": r"aws\s+waf|request blocked.*aws"},
    {"name": "Akamai",          "type": "header",   "header": "x-check-cacheable",       "pattern": r".*"},
    {"name": "Akamai",          "type": "header",   "header": "x-akamai-transformed",    "pattern": r".*"},
    {"name": "Akamai",          "type": "body",     "pattern": r"akamai.*reference|reference.*akamai"},
    {"name": "Imperva Incapsula","type": "cookie",  "cookie": "incap_ses",               "pattern": r".*"},
    {"name": "Imperva Incapsula","type": "cookie",  "cookie": "visid_incap",             "pattern": r".*"},
    {"name": "Imperva Incapsula","type": "body",     "pattern": r"incapsula incident id|powered by incapsula"},
    {"name": "F5 BIG-IP ASM",   "type": "cookie",   "cookie": "ts",                      "pattern": r"^[0-9a-f]{32,}"},
    {"name": "F5 BIG-IP ASM",   "type": "header",   "header": "x-cnection",              "pattern": r".*"},
    {"name": "F5 BIG-IP ASM",   "type": "body",     "pattern": r"f5.*the requested url|reference id.*big-ip"},
    {"name": "Sucuri",          "type": "header",   "header": "x-sucuri-id",             "pattern": r".*"},
    {"name": "Sucuri",          "type": "header",   "header": "x-sucuri-cache",          "pattern": r".*"},
    {"name": "Sucuri",          "type": "body",     "pattern": r"sucuri website firewall|access denied.*sucuri"},
    {"name": "ModSecurity",     "type": "header",   "header": "server",                  "pattern": r"mod_security|modsec"},
    {"name": "ModSecurity",     "type": "body",     "pattern": r"mod_security|this error.*generated by mod_security|not acceptable.*modsec"},
    {"name": "Barracuda",       "type": "cookie",   "cookie": "barra_counter_session",   "pattern": r".*"},
    {"name": "Barracuda",       "type": "body",     "pattern": r"barracuda.*application.*firewall"},
    {"name": "Wordfence",       "type": "body",     "pattern": r"wordfence|generated by wordfence"},
    {"name": "Wordfence",       "type": "header",   "header": "x-fw-hash",               "pattern": r".*"},
    {"name": "DenyAll",         "type": "cookie",   "cookie": "sessioncookie",           "pattern": r".*"},
    {"name": "DenyAll",         "type": "body",     "pattern": r"denyall|naxsi"},
    {"name": "Fortinet FortiWeb","type": "header",  "header": "x-waf-event-info",        "pattern": r".*"},
    {"name": "Fortinet FortiWeb","type": "cookie",  "cookie": "cookiesession1",          "pattern": r".*"},
    {"name": "Fortinet FortiWeb","type": "body",     "pattern": r"fortigate|fortiweb"},
    {"name": "SonicWall",       "type": "body",     "pattern": r"sonicwall|this request is blocked by the sonicwall"},
    {"name": "Wallarm",         "type": "header",   "header": "x-wallarm-node-uuid",     "pattern": r".*"},
    {"name": "Wallarm",         "type": "body",     "pattern": r"wallarm"},
    {"name": "Alibaba Cloud WAF","type": "header",  "header": "ali-cdn-real-ip",         "pattern": r".*"},
    {"name": "Alibaba Cloud WAF","type": "body",     "pattern": r"error 405.*http error"},
    {"name": "Tencent Cloud WAF","type": "body",     "pattern": r"tencent"},
    {"name": "Huawei Cloud WAF", "type": "header",  "header": "x-hss-waf",              "pattern": r".*"},
    {"name": "Azure Front Door", "type": "header",  "header": "x-azure-ref",            "pattern": r".*"},
    {"name": "Azure Front Door", "type": "body",     "pattern": r"microsoft azure|our.*services are not available"},
    {"name": "Fastly",          "type": "header",   "header": "x-fastly-request-id",    "pattern": r".*"},
    {"name": "Varnish",         "type": "header",   "header": "x-varnish",              "pattern": r".*"},
    {"name": "Varnish",         "type": "header",   "header": "via",                    "pattern": r"varnish"},
    {"name": "Nginx Plus",      "type": "header",   "header": "server",                 "pattern": r"nginx.*plus"},
    {"name": "Palo Alto NGFW",  "type": "body",     "pattern": r"palo alto.*application.*blocked"},
    {"name": "Citrix NetScaler","type": "cookie",   "cookie": "ns_af",                  "pattern": r".*"},
    {"name": "Citrix NetScaler","type": "header",   "header": "via",                    "pattern": r"netscaler"},
    {"name": "Radware AppWall", "type": "body",     "pattern": r"radware|appwall"},
    {"name": "Comodo WAF",      "type": "body",     "pattern": r"comodo waf"},
    {"name": "Signal Sciences", "type": "header",   "header": "x-sigsci-requestid",     "pattern": r".*"},
    {"name": "Reblaze",         "type": "cookie",   "cookie": "rbzid",                  "pattern": r".*"},
    {"name": "StackPath",       "type": "body",     "pattern": r"stackpath|highwinds"},
    {"name": "KeyCDN",          "type": "header",   "header": "x-cache",                "pattern": r"keycdn"},
    {"name": "Limelight",       "type": "header",   "header": "x-ll-sid",               "pattern": r".*"},
]

CDN_SIGNATURES = {
    "Cloudflare":  ["cf-ray", "cf-cache-status", "cf-request-id"],
    "Akamai":      ["x-akamai-transformed", "akamai-origin-hop"],
    "Fastly":      ["x-fastly-request-id", "x-served-by", "x-cache-hits"],
    "MaxCDN":      ["x-cache", "x-pull-zone"],
    "BunnyCDN":    ["cdn-pullzone", "cdn-requestcountrycode"],
    "Varnish":     ["x-varnish", "age"],
    "Sucuri CDN":  ["x-sucuri-id"],
    "KeyCDN":      ["x-cache"],
}

# ── Bypass payloads ──────────────────────────────────────────────────────────
BYPASS_PAYLOADS = [
    "/?id=1 UNION SELECT 1,2,3--",
    "/?id=1' OR '1'='1",
    "/?q=<script>alert(1)</script>",
    "/?file=../../../etc/passwd",
    "/?cmd=id;ls",
    "/?search=\x00' OR 1=1--",
    "/?id=%27%20OR%201%3D1--",
    "/?id=1/*!UNION*//*!SELECT*/1,2,3--",
    "/?id=1 AND 1=1",
    "/?foo=bar&id=1 OR SLEEP(3)--",
]

BYPASS_TECHNIQUES: Dict[str, List[str]] = {
    "Cloudflare": [
        "Use origin IP directly (find via Shodan/SecurityTrails/old DNS records)",
        "Try HTTP/2 smuggling (CVE-2023-44487 style)",
        "Unicode normalization: é → e bypass",
        "JSON body injection instead of URL params",
        "CloudFlare Workers abuse for origin bypass",
        "Encode payload: /%2F..%2F..%2F",
    ],
    "AWS WAF": [
        "Use HTTP/1.0 in requests to avoid host-based rules",
        "Fragment SQL: SE/**/LECT instead of SELECT",
        "Chunked transfer encoding bypass",
        "Base64 encode payloads where decoded server-side",
        "Vary parameter case: Id vs id vs ID",
    ],
    "ModSecurity": [
        "Null byte injection: %00",
        "Double URL encoding: %2527 → %27 → '",
        "Content-Type manipulation: application/json vs form",
        "HTTP verb tampering (PUT/PATCH vs POST)",
        "Multipart form boundary tricks",
        "HPP (HTTP Parameter Pollution)",
    ],
    "Akamai": [
        "Try legacy API endpoint versions",
        "X-Forwarded-For: 127.0.0.1 spoofing",
        "X-Remote-IP / X-Originating-IP headers",
        "Use Akamai's own IP ranges as source",
        "CNAME origin discovery",
    ],
    "Generic": [
        "Header injection: X-Forwarded-For, X-Real-IP, X-Custom-IP-Authorization",
        "Case variation: SeLeCt, uNiOn",
        "Comment injection: /*!SELECT*/, --+, #",
        "Hex encoding: 0x53454c454354 (SELECT)",
        "Unicode full-width: ｓｅｌｅｃｔ",
        "Whitespace alternatives: \\t, \\n, /**/ between keywords",
        "Try /v2/, /api/v1/, /graphql endpoints (often less restricted)",
        "Slow-rate attack to evade threshold rules",
        "Try PATCH/PUT instead of POST for same endpoint",
    ],
}


# ── Detection logic ──────────────────────────────────────────────────────────

def _fetch(url: str, payload: str = "") -> Optional[requests.Response]:
    try:
        s = requests.Session()
        s.headers.update({
            "User-Agent":      "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)",
            "Accept":          "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5",
            "Connection":      "close",
        })
        target = url + payload
        return s.get(target, timeout=TIMEOUT, verify=False, allow_redirects=True)
    except Exception as e:
        warning(f"[Fetch] {e}")
        return None


def _detect_waf_from_response(resp: requests.Response) -> List[str]:
    detected = []
    if not resp:
        return detected

    headers = {k.lower(): v.lower() for k, v in resp.headers.items()}
    body    = resp.text.lower()
    cookies = {k.lower(): v for k, v in resp.cookies.items()}

    seen = set()
    for sig in WAF_SIGNATURES:
        name = sig["name"]
        if name in seen:
            continue

        matched = False
        if sig["type"] == "header":
            hval = headers.get(sig["header"].lower(), "")
            if re.search(sig["pattern"], hval, re.I):
                matched = bool(hval)
        elif sig["type"] == "cookie":
            cval = cookies.get(sig["cookie"].lower(), "")
            if re.search(sig["pattern"], cval, re.I):
                matched = bool(cval)
        elif sig["type"] == "body":
            matched = bool(re.search(sig["pattern"], body, re.I))

        if matched:
            detected.append(name)
            seen.add(name)

    return detected


def _detect_cdn(headers: Dict) -> List[str]:
    detected = []
    h = {k.lower(): v for k, v in headers.items()}
    for cdn, indicators in CDN_SIGNATURES.items():
        if any(ind.lower() in h for ind in indicators):
            detected.append(cdn)
    return detected


def _behavioral_analysis(url: str) -> Dict:
    """Send malicious payloads and analyze responses."""
    results = {
        "blocking": False,
        "block_codes": [],
        "block_payloads": [],
        "detection_rate": 0.0,
        "block_count": 0,
    }

    block_count = 0
    for payload in BYPASS_PAYLOADS:
        resp = _fetch(url, payload)
        if resp is not None:
            if resp.status_code in (403, 406, 429, 503, 501) or \
               re.search(r"access denied|blocked|forbidden|illegal|attack", resp.text, re.I):
                block_count += 1
                results["block_codes"].append(resp.status_code)
                results["block_payloads"].append(payload)
        time.sleep(0.5)

    results["block_count"]     = block_count
    results["blocking"]        = block_count > 0
    results["detection_rate"]  = round(block_count / len(BYPASS_PAYLOADS) * 100, 1)
    return results


def _fingerprint_server(resp: requests.Response) -> Dict:
    headers = dict(resp.headers)
    server  = headers.get("Server", headers.get("server", "Unknown"))
    return {
        "server":        server,
        "x_powered_by":  headers.get("X-Powered-By", ""),
        "content_type":  headers.get("Content-Type", ""),
        "x_frame":       headers.get("X-Frame-Options", ""),
        "csp":           headers.get("Content-Security-Policy", ""),
        "hsts":          headers.get("Strict-Transport-Security", ""),
        "cors":          headers.get("Access-Control-Allow-Origin", ""),
    }


# ── Main entry point ─────────────────────────────────────────────────────────

def run_waf_detect(target: str) -> Dict:
    section_header("WAF Detection & Bypass Engine", "Ultra 35+ Vendor Detection")
    info(f"Target: {target}")

    # Normalize URL
    if not target.startswith("http"):
        urls = [f"https://{target}", f"http://{target}"]
    else:
        urls = [target]

    base_url   = None
    base_resp  = None
    for u in urls:
        info(f"Trying: {u}")
        r = _fetch(u)
        if r:
            base_url  = u
            base_resp = r
            success(f"Connected: {u}  [{r.status_code}]")
            break

    if not base_resp:
        error("Cannot reach target")
        return {}

    # Normal response fingerprint
    fp = _fingerprint_server(base_resp)
    info(f"Server: {fp['server']}")

    # WAF detection from normal response
    waf_from_normal = _detect_waf_from_response(base_resp)

    # Behavioral analysis (send payloads)
    info("Running behavioral analysis with attack payloads...")
    behavior = _behavioral_analysis(base_url)

    # Also check WAF from malicious payload responses
    waf_from_attack: List[str] = []
    for payload in BYPASS_PAYLOADS[:5]:
        resp = _fetch(base_url, payload)
        if resp:
            waf_from_attack.extend(_detect_waf_from_response(resp))
        time.sleep(0.3)

    # Combine detected WAFs
    all_detected = list(set(waf_from_normal + waf_from_attack))

    # CDN detection
    cdns = _detect_cdn(dict(base_resp.headers))

    # Security headers check
    sec_headers = {
        "HSTS":           bool(fp["hsts"]),
        "CSP":            bool(fp["csp"]),
        "X-Frame-Options": bool(fp["x_frame"]),
        "CORS":           fp["cors"],
    }

    # Bypass suggestions
    bypass_suggestions = []
    for waf in all_detected:
        bypass_suggestions.extend(BYPASS_TECHNIQUES.get(waf, []))
    if not bypass_suggestions:
        bypass_suggestions = BYPASS_TECHNIQUES["Generic"]

    # ── Print results ────────────────────────────────────────────────────────
    console.print("\n[bold cyan]━━━ WAF DETECTION RESULTS ━━━[/bold cyan]")

    if all_detected:
        for waf in all_detected:
            found(f"  [bold red]WAF DETECTED:[/bold red]  {waf}")
    else:
        console.print("  [green]No WAF signature matched[/green]")

    if cdns:
        info(f"CDN: {', '.join(cdns)}")

    console.print(f"\n  Server:        {fp['server']}")
    console.print(f"  X-Powered-By:  {fp['x_powered_by'] or '—'}")
    console.print(f"  HSTS:          {'✓' if sec_headers['HSTS'] else '✗'}")
    console.print(f"  CSP:           {'✓' if sec_headers['CSP'] else '✗'}")
    console.print(f"  X-Frame:       {'✓' if sec_headers['X-Frame-Options'] else '✗'}")

    console.print(f"\n[bold cyan]━━━ BEHAVIORAL ANALYSIS ━━━[/bold cyan]")
    console.print(f"  Payloads tested:  {len(BYPASS_PAYLOADS)}")
    console.print(f"  Payloads blocked: {behavior['block_count']}")
    console.print(f"  Detection rate:   {behavior['detection_rate']}%")
    console.print(f"  Blocking active:  {'[red]YES[/red]' if behavior['blocking'] else '[green]NO[/green]'}")

    if behavior["block_codes"]:
        codes = sorted(set(behavior["block_codes"]))
        console.print(f"  Block codes:      {codes}")

    console.print("\n[bold cyan]━━━ BYPASS TECHNIQUES ━━━[/bold cyan]")
    for i, tip in enumerate(bypass_suggestions[:10], 1):
        console.print(f"  [yellow]{i:2d}.[/yellow]  {tip}")

    print_summary("WAF Detection", {
        "WAF Detected":    ", ".join(all_detected) or "None",
        "CDN":             ", ".join(cdns) or "None",
        "Detection Rate":  f"{behavior['detection_rate']}%",
        "Payloads Blocked":behavior["block_count"],
        "HSTS":            sec_headers["HSTS"],
        "CSP":             sec_headers["CSP"],
    })

    return {
        "waf":            all_detected,
        "cdn":            cdns,
        "behavior":       behavior,
        "server_fingerprint": fp,
        "security_headers":   sec_headers,
        "bypass_techniques":  bypass_suggestions,
    }
