"""
report_gen.py — Ultra Report Generator
Formats: HTML (interactive), JSON (machine-readable), Markdown (readable)
"""

import json
import os
from datetime import datetime
from typing import Dict, Any


def _now():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def _slug():
    return datetime.now().strftime("%Y%m%d_%H%M%S")


# ── JSON ──────────────────────────────────────────────────────────────────────

def save_json(data: Dict, target: str, output_dir: str = "reports") -> str:
    os.makedirs(output_dir, exist_ok=True)
    filename = os.path.join(output_dir, f"recon_{target.replace('.','_')}_{_slug()}.json")
    with open(filename, "w") as f:
        json.dump(data, f, indent=2, default=str)
    return filename


# ── Markdown ─────────────────────────────────────────────────────────────────

def save_markdown(data: Dict, target: str, output_dir: str = "reports") -> str:
    os.makedirs(output_dir, exist_ok=True)
    filename = os.path.join(output_dir, f"recon_{target.replace('.','_')}_{_slug()}.md")

    lines = [
        f"# Recon Toolkit Pro — Report",
        f"",
        f"**Target:** `{target}`  ",
        f"**Date:** {_now()}  ",
        f"**Tool:** Recon Toolkit Pro v3.2 Ultra",
        f"",
        f"---",
        f"",
    ]

    def _section(title, content):
        lines.append(f"## {title}")
        lines.append("")
        if isinstance(content, dict):
            for k, v in content.items():
                lines.append(f"- **{k}:** {v}")
        elif isinstance(content, list):
            for item in content:
                lines.append(f"- {item}")
        else:
            lines.append(str(content))
        lines.append("")

    for module, result in data.items():
        if isinstance(result, dict):
            _section(module.replace("_", " ").title(), result)

    with open(filename, "w") as f:
        f.write("\n".join(lines))
    return filename


# ── HTML ──────────────────────────────────────────────────────────────────────

def save_html(data: Dict, target: str, output_dir: str = "reports") -> str:
    os.makedirs(output_dir, exist_ok=True)
    filename = os.path.join(output_dir, f"recon_{target.replace('.','_')}_{_slug()}.html")

    # Build sections
    sections_html = ""
    for module, result in data.items():
        title = module.replace("_", " ").title()
        content_json = json.dumps(result, indent=2, default=str)
        sections_html += f"""
        <div class="section">
          <h2>{title}</h2>
          <pre class="json">{content_json}</pre>
        </div>
        """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Recon Report — {target}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ background: #0d1117; color: #c9d1d9; font-family: 'Segoe UI', monospace; }}
    header {{ background: linear-gradient(135deg, #161b22, #1f2937); padding: 24px 32px; border-bottom: 1px solid #30363d; }}
    header h1 {{ font-size: 1.8rem; color: #58a6ff; }}
    header .meta {{ color: #8b949e; margin-top: 8px; font-size: 0.9rem; }}
    .container {{ max-width: 1200px; margin: 0 auto; padding: 24px; }}
    .section {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; margin-bottom: 24px; overflow: hidden; }}
    .section h2 {{ background: #1f2937; padding: 12px 20px; font-size: 1rem; color: #58a6ff; border-bottom: 1px solid #30363d; }}
    .json {{ padding: 16px 20px; font-size: 0.82rem; overflow-x: auto; white-space: pre-wrap; color: #e6edf3; line-height: 1.6; }}
    .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: bold; }}
    .critical {{ background: #f851498a; color: #fff; }}
    .high {{ background: #d29922a0; color: #fff; }}
    footer {{ text-align: center; padding: 24px; color: #484f58; font-size: 0.85rem; border-top: 1px solid #21262d; margin-top: 32px; }}
  </style>
</head>
<body>
  <header>
    <h1>🛡 Recon Toolkit Pro v3.2 — Intelligence Report</h1>
    <div class="meta">
      Target: <strong>{target}</strong> &nbsp;|&nbsp;
      Generated: {_now()} &nbsp;|&nbsp;
      Modules: {len(data)}
    </div>
  </header>
  <div class="container">
    {sections_html}
  </div>
  <footer>Generated by Recon Toolkit Pro v3.2 Ultra — For authorized use only</footer>
</body>
</html>"""

    with open(filename, "w") as f:
        f.write(html)
    return filename


# ── Master save ───────────────────────────────────────────────────────────────

def save_all(data: Dict, target: str, output_dir: str = "reports"):
    from ui.rich_ui import console, success
    json_path = save_json(data, target, output_dir)
    md_path   = save_markdown(data, target, output_dir)
    html_path = save_html(data, target, output_dir)
    success(f"JSON report:     {json_path}")
    success(f"Markdown report: {md_path}")
    success(f"HTML report:     {html_path}")
    return {"json": json_path, "markdown": md_path, "html": html_path}
